### ISSUE TITLE
How about implementing fixed percentage of token burning when paying for channel?

### ISSUE THREAD

**Issue by shlavik** [mysteriumnetwork/payments-smart-contracts#62]
How about implementing fixed percentage of token burning when paying for channel to provide deflation tokenomics?

**Comment by chompomonim** [comment]
This is quite radical proposal which would change tokenomics quite a lot. This also doesn't look sustainable for long run because it would limit amount of channel topups.
 
If amount of burning tokens is super small, then it would not make any impact on tokenomics and makes no sense. 

If amount is significant, then if network is successful after 5 or 10 years most of tokens will be burned. Also it would make network more expensive to use.

**Comment by chompomonim** [comment]
We're not planning token burning.
